### PR TITLE
v1-toolkit now sends Access-Control-Allow-Origin: *

### PR DESCRIPTION
**Pull request by waded**
This is the change I'd make for #3856. We've tested this change and it works for the scenario described, as compared to ionic@4.10.2 where .tpl.html requests fail.

### CODE REVIEW

**Comment by Matttaylor8910** [comment]
This looks great! I need this in one of my projects as well for a specific dev scenario.

**Comment by dwieeb** [comment]
Do you think a better solution would be to use the CORS middleware? https://expressjs.com/en/resources/middleware/cors.html

**Comment by waded** [comment]
@dwieeb I considered that and even implemented & tested with that, but it was overkill in our scenario. We did not e.g. need OPTIONS support.

**Comment by waded** [comment]
@dwieeb (I also noted that angular-cli did not do anything more than add the single header, and I did not see anyone asking for more than what they'd done for `ng serve`.)

**Comment by waded** [comment]
That said, if you're OK w/ v1-toolkit taking on those dependencies, I'd be happy to resubmit this w/ usage of the cors middleware instead.

**Comment by dwieeb** [comment]
@waded All good, just wanted your thoughts on it.

I'm not sure why CI is failing. Might be a typescript 3.3.3 issue.

**Comment by dwieeb** [comment]
Thanks @waded! This is great work 🍻

**Comment by waded** [comment]
Thanks for getting this in! I'll leave #3856 be for you to close once this releases or when you see fit.

**Pull request merged**
