### PR TITLE
add v4 Issue thread URL README.md

### PR DESCRIPTION
**Pull request by rdlabo**

### CODE REVIEW

**Comment by dwieeb** [comment]
@rdlabo The issue you're linking to is for testing the tooling of Ionic Angular 4, not CLI v4 itself.

**Comment by dwieeb** [comment]
I think if people have issues with CLI v4 they can just create issues.

**Comment by rdlabo** [comment]
sorry, I was misunderstanding.

I rewrite and update README. and if you do not need it, please close this pull requests

**Comment by dwieeb** [comment]
Thanks @rdlabo !

**Pull request merged**
