### PR TITLE
feat(generate): add cliFragment for guard option

### PR DESCRIPTION
**Pull request by rdlabo**
Add option for guard implements. => https://github.com/ionic-team/ionic-cli/issues/4058
`implements` is reserved name of tslint. so created `cliFragment` and control.

Thanks.

### CODE REVIEW

**Comment by dwieeb** [comment]
@rdlabo I think what we wanted to do to resolve https://github.com/ionic-team/angular-toolkit/issues/159 is to simply remove all the prompts from the Ionic CLI and rely on those in the Angular CLI.

**Comment by rdlabo** [comment]
Sure. I will close this pull request. Thanks for review!!

**Comment by dwieeb** [comment]
Thank you for looking into this! 💙

**Comment by rdlabo** [comment]
If it is possible, please review this pull request.
https://github.com/ionic-team/angular-toolkit/pull/176

Now, I'm writing Ionic guide book, and I want to guide `dynamic import`.
Thanks.

**Pull request closed without merging**
