### PR TITLE
Minor changes to make npm commands run on Windows -- Issue #2967

### PR DESCRIPTION
**Pull request by Tiberriver256**
Fix is for Issue #2967 

-- Replaced all 'rm -rf' with rimraf
-- Replaced single quote in lerna exec npm script with double quote to make Windows happy

### CODE REVIEW

**Comment by dwieeb** [comment]
Sorry for the giant red X. I don't really like that UX choice by github.

**Comment by Tiberriver256** [comment]
No worries. 

I was reading a bit on the Lerna, am I understanding that right that if I install it as a dev dependency in the root package lerna will make sure it's installed in all the sub-packages?

**Comment by dwieeb** [comment]
It doesn't install it in the subpackages. We're actually not doing what they recommend (read https://github.com/lerna/lerna#common-devdependencies). Lerna recommends doing what you've done with `rimraf`, but for now, we're running npm scripts _only_ in the root package, which alters PATH and lets you use `rimraf`, `tsc`, `tslint`, `jest`, etc when using `lerna run`.

For example if the `npm run clean` command is run in the root, it adds `<root>/node_modules/.bin` (where all the binaries are) to PATH, runs `lerna run clean`, which runs each package's "clean" npm script, which references the `rimraf` binary. So it works as long as you don't run `npm run clean` in the subpackages. 

What we're doing is not ideal. What you've done is probably better, but we'll have to add all packages with binaries to each subpackage to be consistent. I'll merge it. 👍

**Comment by dwieeb** [comment]
@Tiberriver256 I found a BOM inserted in package.json. Please configure your text editor to no include BOMs as they can have super weird effects on files, at least in Linux/BSD systems: https://github.com/ionic-team/ionic-cli/commit/e2e1465f890aac73fe119cef3788e8d1b25dd617

more info: https://en.wikipedia.org/wiki/Byte_order_mark

**Pull request merged**
