### PR TITLE
be able to use --source-map flag in cordova.

### PR DESCRIPTION
**Pull request by rdlabo**
@dwieeb ng-toolkit change kebab-case to camel-case. So set kebab-case option.
It may work. But I don't understand how to test ng-toolkit. Please tell me how to install develop ng-toolkit in local v4 project.
( * this week, I can't develop more. If you'd like, please test it )

Resolves https://github.com/ionic-team/ionic-cli/issues/3515

### CODE REVIEW

**Comment by dwieeb** [comment]
The devkit uses camel case, but options can be passed in as camel case or kebab case, so `--sourceMap` and `--source-map` will work.

This looks good so far. We just need to forward the source map preference to the Angular builders.

**Comment by rdlabo** [comment]
@dwieeb I'm sorry to be late. It worked, and I remove Issue title `WIP` .

**Comment by dwieeb** [comment]
No worries, thanks!

**Comment by dwieeb** [comment]
@rdlabo Please take out the `skipLibCheck`. Then, I will merge 👍

**Comment by rdlabo** [comment]
@dwieeb Oops! Sorry! fix and rebased!!

**Pull request merged**
