### PR TITLE
@ionic/v1-toolkit: Add compatibility with gulp v4 file

### PR DESCRIPTION
**Pull request by blavenie**
- Before executing the 'ionic:serve:before' task, detect if `gulpfile.js` has some exported function, as a standard gulp v4 file.
- If v4 file is detected, then define all exported fucntions as gulv v3 task using `gulp.task(<name>, [], exportedFunction)`

This PR should fix the issue #4114

Example of `gulpfile.js` : 
```javascript
const gulp = require('gulp'),
  sass = require('gulp-sass');

function sassTask(done) {
  return gulp.src('./scss/ionic.app.scss')
    .pipe(sass()).on('error', sass.logError)
    .pipe(gulp.dest('./www/css/'))
    .on('end', done); 
}

function watchTask(done) {
    gulp.watch('./scss/ionic.app.scss', sassTask);
    done();
}

(...)
// Define exported task (in the gulp v4 way)
exports.sass = executeSass;
exports['ionic:serve:before'] = gulp.series(sassTask, watchTask);

```
Example of `package.json` : 
```json
devDependencies : {
  "gulp": "4.0.2",
  "gulp-sass": "^4.0.2",
  "node-sass": "^4.13.0"
   (...)
}
```

### CODE REVIEW

**Comment by dwieeb** [comment]
This looks good, but will need some cleanup so the build process finishes

**Comment by blavenie** [comment]
> will need some cleanup so the build process finishes

Can you explain to me ? What do you expected from me ?

**Comment by dwieeb** [comment]
The CI build is failing due to TS compilation errors. They will need to be fixed before this is merged. Thanks!

**Comment by asa47** [comment]
Hello @blavenie and @dwieeb,
Any update on this issue? Or any advice on how to fix it?

**Comment by blavenie** [comment]
ok @dwieeb, all JS error seems to be fixed :)

**Comment by dwieeb** [comment]
Awesome! Thanks!!

**Comment by dwieeb** [comment]
`@ionic/v1-toolkit@3.2.0` is released with this feature! Great work. 🍻

**Comment by rodrigograca31** [comment]
In my opinion, this still needs more work.

If you still support an ionic v1 app nowadays with the node version 12 we have to use gulp 4

You can update your `gulpfile.js` and gulp version to 4 and then run `gulp default` or whatever your task is but when you run `ionic serve` it will run gulp 3.9 even if we installed gulp 4 because `@ionic/v1-toolkit` depends on it.

Actually it runs other gulp stuff and then it checks for tasks called `ionic:serve:before` and etc and runs them
```
> ionic-v1 serve --host=localhost --port=8100 --livereload-port=35729 --dev-port=53703 --engine=browser
[v1] 2020-07-29T11:52:24.764Z ionic:v1-toolkit:lib:gulp Using gulpfile: /home/USER/git/PROJECT/gulpfile.js
[v1] 2020-07-29T11:52:24.765Z ionic:v1-toolkit:lib:gulp Using gulp: /home/USER/git/PROJECT/node_modules/@ionic/v1-toolkit/node_modules/gulp/index.js
[v1] [12:52:24] Serving directory www
[v1] [12:52:24] Cannot load gulp: ReferenceError: primordials is not defined
```

Upon further inspection it breaks here:
because it requires gulp and its 3.9 with node 12 and that explodes 💥
```
try {
            const gulpPath = require.resolve('gulp');
            debug(`Using gulp: ${gulpPath}`);
            _gulpInst = require(gulpPath);
        }
        catch (e) {
            if (e.code !== 'MODULE_NOT_FOUND') {
                throw e;
            }
            throw new Error(chalk.red(`Cannot find module 'gulp'`));
        }
```

Related: #4114 

There should be a way to either use the globally installed gulp or a locally installed one on the main `package.json` instead of the one that comes with `@ionic/v1-toolkit`

These are the critical lines:
```
const gulpPath = require.resolve('gulp');
            debug(`Using gulp: ${gulpPath}`);
            _gulpInst = require(gulpPath);
```

**Pull request merged**
