### PR TITLE
fix(resources): fix hanging issue while transforming images

### PR DESCRIPTION
**Pull request by dwieeb**
This will fix the "hanging" issue explained in https://github.com/ionic-team/ionic-cli/issues/3398 by introducing another step, which is always piping the response to a temporary file and collecting image transform results before copying the transformed images to the project.

Fixes https://github.com/ionic-team/ionic-cli/issues/3398
Fixes https://github.com/ionic-team/ionic-cli/issues/3385

### CODE REVIEW

**Comment by dwieeb** [comment]
This bug was introduced while attempting to fix this issue: https://github.com/ionic-team/ionic-cli/issues/3005

**Comment by dwieeb** [comment]
Additionally, this appears to fix the ERR_STREAM_DESTROYED issue.

Fixes https://github.com/ionic-team/ionic-cli/issues/3385

**Comment by cam1708** [comment]
Hi there, I seem to still get this issue even in CLI 4.2.1

**Comment by dwieeb** [comment]
This issue will track it: https://github.com/ionic-team/ionic-cli/issues/3540

**Pull request merged**
