### PR TITLE
feat: add support for pnpm

### PR DESCRIPTION
**Pull request by muuvmuuv**
This PR adds support for the package manager `pnpm`.

More info about `pnpm `: https://pnpm.js.org/en/

Closes: #4285

### CODE REVIEW

**Comment by dwieeb** [comment]
@muuvmuuv This is great!

One question: it seems like pnpm need the `--` arg separator (like in npm) for `pnpm run` (see https://pnpm.js.org/en/cli/run#synopsis)

It looks like it's not being added: https://github.com/ionic-team/ionic-cli/pull/4330/files#diff-1b40833217c4862ef2a34651e286cc04R214

**Comment by muuvmuuv** [comment]
@dwieeb oh yes! Sorry. I will fix it probably next week but we are celebrating carnival this weeks so it might be delayed

**Comment by dwieeb** [comment]
Awesome work!!

**Comment by aparajita** [comment]
While this is appreciated, it doesn't quite go all the way. `ionic build` fails because of this line:

https://github.com/ionic-team/ionic-cli/blob/483d9ab593c4715ab21b3b721c6735c7e01d367e/packages/%40ionic/cli/src/lib/build.ts#L47

**Comment by muuvmuuv** [comment]
Any idea how I could test this @aparajita ? I think the best is to have a test that build a sample ionic ng/vue/etc. project. cc: @dwieeb

**Comment by aparajita** [comment]
@muuvmuuv In any ionic project, set `npmClient=pnpm` in `ionic.config.js`, run `ionic build`, and it will fail.

**Comment by muuvmuuv** [comment]
No, I mean with Jest @aparajita so future added pm's (if there will be any)  will not fail or updated API's

**Comment by aparajita** [comment]
Here are the conditions under which it fails:

In `package.json`, assuming you have a "build" script:

```json
"scripts": {
  "ionic:build": "pnpm run build"
}
```

Then in a terminal:

```sh
ionic config set npmClient pnpm
ionic config set type custom
ionic build
```

You get this output:

```
> yarn run --non-interactive ionic:build

[ERROR] yarn is required for this command to work properly.
```

**Comment by aparajita** [comment]
I should point out I don't have yarn installed and never will. 😁

**Comment by aparajita** [comment]
@muuvmuuv I have a working fix, I'll make a PR later today.

**Comment by muuvmuuv** [comment]
Great, set me on CC I would love to have a look at it. I also have worked on a fix but couldn't test it.

**Comment by aparajita** [comment]
I have **ionic** fixed, but **capacitor** still needs fixing unfortunately. And it's a much bigger job.

**Comment by aparajita** [comment]
I'm quite surprised that the authors of capacitor wrote the code in a binary way: if you're not using yarn, you must be using npm. As if the universe of package managers would eternally remain the same! 🙄

**Comment by aparajita** [comment]
Hey @muuvmuuv, the PR is here: https://github.com/ionic-team/ionic-cli/pull/4459

**Pull request merged**
